### ISSUE TITLE
ERROR: Failed building wheel for django-chroniker‌

### ISSUE THREAD

**Issue by rafa-munoz** [chrisspen/django-chroniker#155]
Command executed: `pip3 install -r requirements.txt` (this file contains chroniker).

```
  Building wheel for django-chroniker (setup.py): started
  Building wheel for django-chroniker (setup.py): finished with status 'error'
  ERROR: Complete output from command &#x2F;usr&#x2F;bin&#x2F;python3 -u -c &#x27;import setuptools, tokenize;__file__=&#x27;&quot;&#x27;&quot;&#x27;&#x2F;tmp&#x2F;pip-install-2i8dqv2a&#x2F;django-chroniker&#x2F;setup.py&#x27;&quot;&#x27;&quot;&#x27;;f=getattr(tokenize, &#x27;&quot;&#x27;&quot;&#x27;open&#x27;&quot;&#x27;&quot;&#x27;, open)(__file__);code=f.read().replace(&#x27;&quot;&#x27;&quot;&#x27;\r\n&#x27;&quot;&#x27;&quot;&#x27;, &#x27;&quot;&#x27;&quot;&#x27;\n&#x27;&quot;&#x27;&quot;&#x27;);f.close();exec(compile(code, __file__, &#x27;&quot;&#x27;&quot;&#x27;exec&#x27;&quot;&#x27;&quot;&#x27;))&#x27; bdist_wheel -d &#x2F;tmp&#x2F;pip-wheel-0g792r6n --python-tag cp36:‌
  ERROR: running bdist_wheel‌
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/chroniker
  copying chroniker/__init__.py -> build/lib/chroniker
  copying chroniker/views.py -> build/lib/chroniker
  copying chroniker/admin.py -> build/lib/chroniker
  copying chroniker/constants.py -> build/lib/chroniker
  copying chroniker/utils.py -> build/lib/chroniker
  copying chroniker/widgets.py -> build/lib/chroniker
  copying chroniker/models.py -> build/lib/chroniker
  copying chroniker/settings.py -> build/lib/chroniker
  creating build/lib/site
  copying site/__init__.py -> build/lib/site
  creating build/lib/chroniker/management
  copying chroniker/management/__init__.py -> build/lib/chroniker/management
  creating build/lib/chroniker/migrations
  copying chroniker/migrations/__init__.py -> build/lib/chroniker/migrations
  copying chroniker/migrations/0001_initial.py -> build/lib/chroniker/migrations
  creating build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0003_auto__add_jobdependency__add_unique_jobdependency_dependent_dependee.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0012_auto__add_field_job_current_hostname__chg_field_job_hostname.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/__init__.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0002_auto__add_field_job_hostname.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0017_auto__add_field_job_raw_command.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0016_auto__add_field_log_hostname__add_field_log_on_time__add_field_job_tim.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0013_auto__add_field_job_current_pid.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0001_initial.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0006_auto__add_field_job_is_monitor.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0014_auto.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0009_auto__add_field_job_monitor_description.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0008_auto__add_field_job_monitor_error_template.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0004_auto__add_field_job_last_run_start_timestamp__add_field_job_total_part.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0015_auto__add_field_job_log_stdout__add_field_job_log_stderr.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0005_auto.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0010_auto__add_field_job_maximum_log_entries.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0011_auto__add_field_job_monitor_records.py -> build/lib/chroniker/south_migrations
  copying chroniker/south_migrations/0007_auto__add_field_job_monitor_url.py -> build/lib/chroniker/south_migrations
  creating build/lib/chroniker/templatetags
  copying chroniker/templatetags/__init__.py -> build/lib/chroniker/templatetags
  copying chroniker/templatetags/chroniker_tags.py -> build/lib/chroniker/templatetags
  creating build/lib/chroniker/tests
  copying chroniker/tests/manage.py -> build/lib/chroniker/tests
  copying chroniker/tests/urls.py -> build/lib/chroniker/tests
  copying chroniker/tests/__init__.py -> build/lib/chroniker/tests
  copying chroniker/tests/views.py -> build/lib/chroniker/tests
  copying chroniker/tests/tests.py -> build/lib/chroniker/tests
  copying chroniker/tests/commands.py -> build/lib/chroniker/tests
  copying chroniker/tests/models.py -> build/lib/chroniker/tests
  copying chroniker/tests/settings.py -> build/lib/chroniker/tests
  creating build/lib/chroniker/management/commands
  copying chroniker/management/commands/run_job.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/__init__.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/test_status_update.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/calculate_job_chain.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/cronserver.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/cron.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/check_monitor.py -> build/lib/chroniker/management/commands
  copying chroniker/management/commands/cron_clean.py -> build/lib/chroniker/management/commands
  creating build/lib/chroniker/tests/management
  copying chroniker/tests/management/__init__.py -> build/lib/chroniker/tests/management
  creating build/lib/chroniker/tests/management/commands
  copying chroniker/tests/management/commands/__init__.py -> build/lib/chroniker/tests/management/commands
  copying chroniker/tests/management/commands/test_error.py -> build/lib/chroniker/tests/management/commands
  copying chroniker/tests/management/commands/test_sleeper.py -> build/lib/chroniker/tests/management/commands
  copying chroniker/tests/management/commands/test_waiter.py -> build/lib/chroniker/tests/management/commands
  copying chroniker/tests/management/commands/test_success.py -> build/lib/chroniker/tests/management/commands
  creating build/lib/chroniker/static
  creating build/lib/chroniker/static/chroniker
  creating build/lib/chroniker/static/chroniker/js
  copying chroniker/static/chroniker/js/dygraph-combined.js -> build/lib/chroniker/static/chroniker/js
  creating build/lib/chroniker/templates
  creating build/lib/chroniker/templates/chroniker
  copying chroniker/templates/chroniker/error_message.txt -> build/lib/chroniker/templates/chroniker
  creating build/lib/chroniker/templates/admin
  creating build/lib/chroniker/templates/admin/chroniker
  creating build/lib/chroniker/templates/admin/chroniker/job
  copying chroniker/templates/admin/chroniker/job/duration_graph.html -> build/lib/chroniker/templates/admin/chroniker/job
  copying chroniker/templates/admin/chroniker/job/change_form.html -> build/lib/chroniker/templates/admin/chroniker/job
  copying chroniker/templates/admin/chroniker/job/change_list.html -> build/lib/chroniker/templates/admin/chroniker/job
  creating build/lib/chroniker/tests/fixtures
  copying chroniker/tests/fixtures/test_jobs.json -> build/lib/chroniker/tests/fixtures
  copying chroniker/tests/fixtures/jobs_by_command_args.json -> build/lib/chroniker/tests/fixtures
  copying chroniker/tests/fixtures/jobs_by_command.json -> build/lib/chroniker/tests/fixtures
  copying chroniker/tests/fixtures/jobs_by_name.json -> build/lib/chroniker/tests/fixtures
  running build_scripts
  creating build/scripts-3.6
  copying and adjusting bin/chroniker -> build/scripts-3.6
  changing mode of build/scripts-3.6/chroniker from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/chroniker
  copying build/lib/chroniker/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker
  copying build/lib/chroniker/views.py -> build/bdist.linux-x86_64/wheel/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/management
  copying build/lib/chroniker/management/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/management
  creating build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/run_job.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/test_status_update.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/calculate_job_chain.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/cronserver.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/cron.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/check_monitor.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  copying build/lib/chroniker/management/commands/cron_clean.py -> build/bdist.linux-x86_64/wheel/chroniker/management/commands
  creating build/bdist.linux-x86_64/wheel/chroniker/static
  creating build/bdist.linux-x86_64/wheel/chroniker/static/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/static/chroniker/js
  copying build/lib/chroniker/static/chroniker/js/dygraph-combined.js -> build/bdist.linux-x86_64/wheel/chroniker/static/chroniker/js
  creating build/bdist.linux-x86_64/wheel/chroniker/migrations
  copying build/lib/chroniker/migrations/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/migrations
  copying build/lib/chroniker/migrations/0001_initial.py -> build/bdist.linux-x86_64/wheel/chroniker/migrations
  creating build/bdist.linux-x86_64/wheel/chroniker/templates
  creating build/bdist.linux-x86_64/wheel/chroniker/templates/chroniker
  copying build/lib/chroniker/templates/chroniker/error_message.txt -> build/bdist.linux-x86_64/wheel/chroniker/templates/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/templates/admin
  creating build/bdist.linux-x86_64/wheel/chroniker/templates/admin/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/templates/admin/chroniker/job
  copying build/lib/chroniker/templates/admin/chroniker/job/duration_graph.html -> build/bdist.linux-x86_64/wheel/chroniker/templates/admin/chroniker/job
  copying build/lib/chroniker/templates/admin/chroniker/job/change_form.html -> build/bdist.linux-x86_64/wheel/chroniker/templates/admin/chroniker/job
  copying build/lib/chroniker/templates/admin/chroniker/job/change_list.html -> build/bdist.linux-x86_64/wheel/chroniker/templates/admin/chroniker/job
  creating build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0003_auto__add_jobdependency__add_unique_jobdependency_dependent_dependee.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0012_auto__add_field_job_current_hostname__chg_field_job_hostname.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0002_auto__add_field_job_hostname.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0017_auto__add_field_job_raw_command.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0016_auto__add_field_log_hostname__add_field_log_on_time__add_field_job_tim.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0013_auto__add_field_job_current_pid.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0001_initial.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0006_auto__add_field_job_is_monitor.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0014_auto.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0009_auto__add_field_job_monitor_description.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0008_auto__add_field_job_monitor_error_template.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0004_auto__add_field_job_last_run_start_timestamp__add_field_job_total_part.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0015_auto__add_field_job_log_stdout__add_field_job_log_stderr.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0005_auto.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0010_auto__add_field_job_maximum_log_entries.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0011_auto__add_field_job_monitor_records.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/south_migrations/0007_auto__add_field_job_monitor_url.py -> build/bdist.linux-x86_64/wheel/chroniker/south_migrations
  copying build/lib/chroniker/admin.py -> build/bdist.linux-x86_64/wheel/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/templatetags
  copying build/lib/chroniker/templatetags/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/templatetags
  copying build/lib/chroniker/templatetags/chroniker_tags.py -> build/bdist.linux-x86_64/wheel/chroniker/templatetags
  copying build/lib/chroniker/constants.py -> build/bdist.linux-x86_64/wheel/chroniker
  copying build/lib/chroniker/utils.py -> build/bdist.linux-x86_64/wheel/chroniker
  copying build/lib/chroniker/widgets.py -> build/bdist.linux-x86_64/wheel/chroniker
  creating build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/manage.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/urls.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/views.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  creating build/bdist.linux-x86_64/wheel/chroniker/tests/management
  copying build/lib/chroniker/tests/management/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management
  creating build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  copying build/lib/chroniker/tests/management/commands/__init__.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  copying build/lib/chroniker/tests/management/commands/test_error.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  copying build/lib/chroniker/tests/management/commands/test_sleeper.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  copying build/lib/chroniker/tests/management/commands/test_waiter.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  copying build/lib/chroniker/tests/management/commands/test_success.py -> build/bdist.linux-x86_64/wheel/chroniker/tests/management/commands
  creating build/bdist.linux-x86_64/wheel/chroniker/tests/fixtures
  copying build/lib/chroniker/tests/fixtures/test_jobs.json -> build/bdist.linux-x86_64/wheel/chroniker/tests/fixtures
  copying build/lib/chroniker/tests/fixtures/jobs_by_command_args.json -> build/bdist.linux-x86_64/wheel/chroniker/tests/fixtures
  copying build/lib/chroniker/tests/fixtures/jobs_by_command.json -> build/bdist.linux-x86_64/wheel/chroniker/tests/fixtures
  copying build/lib/chroniker/tests/fixtures/jobs_by_name.json -> build/bdist.linux-x86_64/wheel/chroniker/tests/fixtures
  copying build/lib/chroniker/tests/tests.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/commands.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/models.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/tests/settings.py -> build/bdist.linux-x86_64/wheel/chroniker/tests
  copying build/lib/chroniker/models.py -> build/bdist.linux-x86_64/wheel/chroniker
  copying build/lib/chroniker/settings.py -> build/bdist.linux-x86_64/wheel/chroniker
  creating build/bdist.linux-x86_64/wheel/site
  copying build/lib/site/__init__.py -> build/bdist.linux-x86_64/wheel/site
  running install_egg_info
  running egg_info
  writing django_chroniker.egg-info/PKG-INFO
  writing dependency_links to django_chroniker.egg-info/dependency_links.txt
  writing requirements to django_chroniker.egg-info/requires.txt
  writing top-level names to django_chroniker.egg-info/top_level.txt
  reading manifest file 'django_chroniker.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'django_chroniker.egg-info/SOURCES.txt'
  Copying django_chroniker.egg-info to build/bdist.linux-x86_64/wheel/django_chroniker-1.0.12.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/django_chroniker-1.0.12.data
  creating build/bdist.linux-x86_64/wheel/django_chroniker-1.0.12.data/scripts
  copying build/scripts-3.6/chroniker -> build/bdist.linux-x86_64/wheel/django_chroniker-1.0.12.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/django_chroniker-1.0.12.data/scripts/chroniker to 755
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2i8dqv2a/django-chroniker/setup.py", line 58, in <module>
      tests_require=get_reqs('requirements-test.txt'),
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 257, in run
      self.distinfo_dir)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 427, in egg2dist
      distribution=self.distribution)
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 177, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 234, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2988, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)
  ----------------------------------------
  ERROR: Failed building wheel for django-chroniker‌
  Running setup.py clean for django-chroniker‌
  Building wheel for django-storages-azure (setup.py): started
  Building wheel for django-storages-azure (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/68/f2/f5/0af4212ccf0e2edb602f89d509c6e8c9b15d59967505aef019
  Building wheel for googlemaps (setup.py): started
  Building wheel for googlemaps (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/3c/3f/25/ce6d7722dba07e5d4a12d27ab38f3d7add65ef43171b02c819
  Building wheel for googleads (setup.py): started
  Building wheel for googleads (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/33/3f/69/a5d82b52c1e5a318e88445fb85b6d748da79e71e61c21852c7
  Building wheel for xhtml2pdf (setup.py): started
  Building wheel for xhtml2pdf (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c3/22/d6/fb20c4c532e9eb3b43fe30df5242c8ebaae20d1a6c4bcfa7b9
  Building wheel for uWSGI (setup.py): started
  Building wheel for uWSGI (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2d/0c/b0/f3ba1bbce35c3766c9dac8c3d15d5431cac57e7a8c4111c268
  Building wheel for itypes (setup.py): started
  Building wheel for itypes (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/7b/52/af/4e27324812e7ab7bbbc30f748d317f3739477562325cb4c723
  Building wheel for coreschema (setup.py): started
  Building wheel for coreschema (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/10/7b/ba/04fcd6b33e6123ca11a5f5ab56decb1a2d87ced028377a1377
  Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/17/08/ec/22b464874958c3fc91e1a75748fae2220eb704a8b1035f9a03
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Building wheel for suds-jurko (setup.py): started
  Building wheel for suds-jurko (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/12/68/53/d3902c054e32115da1d45bac442a547a071a86a65db4d77027
  Building wheel for pyPdf2 (setup.py): started
  Building wheel for pyPdf2 (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/53/84/19/35bc977c8bf5f0c23a8a011aa958acd4da4bbd7a229315c1b7
  Building wheel for dockerpty (setup.py): started
  Building wheel for dockerpty (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e5/1e/86/bd0a97a0907c6c654af654d5875d1d4383dd1f575f77cee4aa
  Building wheel for docopt (setup.py): started
  Building wheel for docopt (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Building wheel for texttable (setup.py): started
  Building wheel for texttable (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/99/1e/2b/8452d3a48dad98632787556a0f2f90d56703b39cdf7d142dd1
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built django-storages-azure googlemaps googleads xhtml2pdf uWSGI itypes coreschema psutil PyYAML suds-jurko pyPdf2 dockerpty docopt texttable pycparser
Failed to build django-chroniker
```

**Comment by chrisspen** [comment]
Following up years late — this no longer reproduces.

Built the wheel from current master:

```
$ pip wheel --no-deps -w /tmp/wheeltest .
Building wheel for django-chroniker (pyproject.toml): finished with status 'done'
Created wheel for django-chroniker: django_chroniker-1.0.24-py3-none-any.whl
Successfully built django-chroniker
```

I could not determine the original cause, and I want to be straight about that rather than guess: the log you pasted was truncated just before the actual error, so it shows every other package building and then `Failed to build django-chroniker` without the traceback that would say why.

A good deal has changed since 2019 — packaging was modernised, the Python 2 support code was removed, and the package now targets Python 3.9-3.12. Any of that could have been it.

Closing since it does not reproduce. If you still hit it, please reopen with the lines immediately **above** `Failed to build django-chroniker` — that is the part that names the error, and with it this would be straightforward to fix.
