### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 33-38: ordinal not in range(128)

### ISSUE THREAD

**Issue by ugvibib** [chrisspen/django-chroniker#240]
linux: Debian GNU/Linux 10 \n \l

```
Traceback (most recent call last):
  File "/usr/local/bin/chroniker", line 114, in <module>
    call_command('cron', jobs=jobs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/chroniker/management/commands/cron.py", line 334, in handle
    sync=options['sync'],
  File "/usr/local/lib/python3.6/site-packages/chroniker/management/commands/cron.py", line 232, in run_cron
    print('Process %s ended.' % (proc,))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 33-38: ordinal not in range(128)
```

**Comment by ugvibib** [comment]
`* * * * * PYTHONIOENCODING=utf-8 /usr/local/bin/chroniker -s YpXstg.settings -p /code > /var/log/chroniker.log 2>&1 &`
