### ISSUE TITLE
Error : select_for_update cannot be used outside of a transaction.

### ISSUE THREAD

**Issue by mwolff44** [chrisspen/django-chroniker#27]
Hello,
## I have this error with the last chroniker version : 

Django Version:     1.6.5
Exception Type:     TransactionManagementError
Exception Value:    
## select_for_update cannot be used outside of a transaction.

/usr/local/venv/lib/python2.7/site-packages/chroniker/models.py in is_due

```
        return q.exists()
...
```

▼ Local vars
Variable    Value
q   
## Error in formatting: select_for_update cannot be used outside of a transaction.

BR

Matt

**Comment by chrisspen** [comment]
Thanks for the report. Can you provide any more details? Is it still happening with the latest version?

**Comment by chrisspen** [comment]
I've been able to reproduce this as well in Django 1.6.

    Traceback (most recent call last):
      File "/usr/local/myproject/src/mysite/manage.py", line 9, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/chroniker/management/commands/cron.py", line 359, in handle
        sync=options['sync'],
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/chroniker/management/commands/cron.py", line 152, in run_cron
        q = Job.objects.due_with_met_dependencies_ordered(jobs=jobs)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/chroniker/models.py", line 373, in due_with_met_dependencies_ordered
        for j in self.due_with_met_dependencies(jobs=jobs))
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/chroniker/models.py", line 372, in <genexpr>
        (j.id, set([_.dependee.id for _ in j.dependencies.all()]))
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/chroniker/models.py", line 330, in due_with_met_dependencies
        for job in self.due():
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
        self._fetch_all()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
        for row in compiler.results_iter():
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
        for rows in self.execute_sql(MULTI):
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
        sql, params = self.as_sql()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 147, in as_sql
        raise TransactionManagementError("select_for_update cannot be used outside of a transaction.")

Temporary workaround is to set `CHRONIKER_SELECT_FOR_UPDATE = False` in your `settings.py`.

**Comment by chrisspen** [comment]
This looks resolved. `is_due()` now wraps the query in an explicit transaction:

```python
q = type(self).objects.due(job=self, **kwargs)
with transaction.atomic():
    res = q.exists()
```

which is exactly what `TransactionManagementError: select_for_update cannot be used outside of a transaction` was asking for. `CHRONIKER_SELECT_FOR_UPDATE` also defaults to `False` now, so the `select_for_update()` path is opt-in rather than always on.

Closing as fixed. Please reopen if it still happens on a current version.
