### ISSUE TITLE
Issue with Python 3

### ISSUE THREAD

**Issue by Alerion** [chrisspen/django-chroniker#48]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/administrator/workspace/fan/adops/eggs/django_chroniker-0.8.1-py3.4.egg/chroniker/models.py", line 168, in run
    self.lock_file.write(str(time.time()))
  File "/usr/lib/python3.4/tempfile.py", line 538, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
```

You can fix with replacing models.py:168 with `self.lock_file.write(str(time.time()).encode('utf-8'))`

**Comment by chrisspen** [comment]
Thanks. This will be fixed in the upcoming 0.8.4 release.
