### ISSUE TITLE
Database lock

### ISSUE THREAD

**Issue by steffenmandrup** [chrisspen/django-chroniker#49]
If the database is very busy with other stuff while saving, i have often experienced that chroniker is unable to release lock on the database, leaving the module in a state where no cron's can be run, untill the database releases the lock due to timeout.

Is there any workaround this?

**Comment by steffenmandrup** [comment]
ERROR 2016-01-13 12:40:39,984 base 29710 140455342683968 Internal Server Error:                                                                                   /admin/chroniker/job/25/stop/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", li                                                                                  ne 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line                                                                                   99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py"                                                                                  , line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", l                                                                                  ine 198, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chroniker/admin.py", line 350, in                                                                                   stop_job_view
    force_stop = True,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line                                                                                   490, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py"                                                                                  , line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py"                                                                                  , line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line                                                                                   53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in                                                                                   __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line                                                                                   53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py"                                                                                  , line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in                                                                                   execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36,                                                                                   in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction                                                                                  ')

after lock is placed i get these errors no matter what i do. Only reboot solves the issue

**Comment by chrisspen** [comment]
Did you try enabling select for update? You shouldn't have to reboot.
MySQL's default timeout is less than a minute.

**Comment by steffenmandrup** [comment]
But why do these locks happen ? i often get them stopping for maybe 8-10 hours, before starting up again.

**Comment by chrisspen** [comment]
It's hard to say. Something might be crashing or hanging, causing a
transaction to not be committed. Do you see anything unusual in the error
logs? Another cause could be that there are multiple chroniker jobs are
running and trying to update their status.

Try added CHRONIKER_SELECT_FOR_UPDATE = True in your settings and see if
that helps.

**Comment by steffenmandrup** [comment]
Aren't the point with chroniker to have an easy way to setup all your cron jobs ? :) Hopefully they don't lock the database while saving their status, thus breaking if other cron jobs try to do the same. Running multiple cron jobs, you should eventually hit the point where they update at the same time. I got several cron's running every 10 min, with different process lengths.

Tried adding the setting you suggested, will post back if it helps :)

**Comment by steffenmandrup** [comment]
This bug still remains =/

The database ends up locked and all jobs freeze and will not run. Debug logs says nothing, so I have absolutely no idea why.

Everytime it happens, one of the cronjobs are stuck on "is fresh" = false and i'm unable to do anything.

Chroniker was moved to it's dedicated mysql instance, so must be chroniker locking something somewhere

**Comment by chrisspen** [comment]
Even if a deadlock occurs, Chroniker shouldn't freeze. Django/MySQL will eventually throw a DatabaseError for the deadlock when that happens. However, I did notice a similar event on one of my systems, where a job was stuck on running but was still recording a heartbeat, indicating it hadn't frozen or encountered a deadlock. Unfortunately, it hasn't happened since, and I've now set a timeout on the job to kill it after an hour.

Let me know if you find a way to reliably reproduce this, and I'll write a unittest for it.

**Comment by steffenmandrup** [comment]
My entire database gets locked, so i can't even access the jobs in the django admin. It requires a mysql reboot to open it up again

**Comment by steffenmandrup** [comment]
The error always happens after is fresh = false, could be a pointer

**Comment by chrisspen** [comment]
Apologies for the long silence on this one.

There is not a workaround I can offer with confidence, because the answer depends on which backend you are on and where the lock is being taken, and the report does not say.

The relevant setting is `CHRONIKER_SELECT_FOR_UPDATE`. When enabled, `Job.objects.due()` calls `select_for_update(nowait=False)`, which takes a row lock and **waits indefinitely** if another transaction holds it. On a busy database that is exactly the "unable to release lock, no crons run until timeout" behaviour you describe. Turning it off is the first thing I would try:

```python
CHRONIKER_SELECT_FOR_UPDATE = False
```

The tradeoff is that it exists to stop two cron runners picking up the same job simultaneously, so disabling it is only safe if you have a single cron process.

To tell whether that is really your problem:

1. Which database backend? (The docstring notes `select_for_update()` is not supported on some MySQL configurations.)
2. Do you have more than one `manage.py cron` running at once, on the same or different hosts?
3. Do you currently have `CHRONIKER_SELECT_FOR_UPDATE` set explicitly, or is it at its default?

If you have moved on in the nine years since — entirely understandable — just say so and I will close this.

**Comment by chrisspen** [comment]
Closing this as addressed, with the reasoning in case it is still relevant to anyone.

The mechanism was `Job.objects.due()` calling `select_for_update(nowait=False)`, which takes a row lock and waits **indefinitely** if another transaction holds it. On a busy database that is exactly the "unable to release lock, no crons run until the database times out" behaviour described.

`CHRONIKER_SELECT_FOR_UPDATE` now defaults to `False`, so that path is opt-in rather than always on. A default install no longer takes those locks at all.

If you do enable it — it exists to stop two cron runners claiming the same job — the tradeoff is unchanged: it is only safe when a single host reads and writes the Job table, which is what the comment beside the setting says.

Also worth noting for anyone arriving here with similar symptoms: #118 (merged) fixed a related case where a job blocked in a database query could not be terminated by its timeout, because SIGTERM does not interrupt a blocked syscall. That could look very similar from the outside — jobs stuck, nothing progressing.

Nine years without a reproduction and the default has changed underneath it, so closing. Happy to reopen if it still occurs on a current version.
