### ISSUE TITLE
raw_command raise io.UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by noisy** [chrisspen/django-chroniker#50]
using `raw_command` always cause this problem:
```
The job failed to run.  The exception was :

fileno


Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/chroniker/models.py", line 1151, in handle_run
    stderr=sys.stderr)

  File "/usr/local/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:

  File "/usr/local/lib/python3.5/subprocess.py", line 914, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)

  File "/usr/local/lib/python3.5/subprocess.py", line 1400, in _get_handles
    c2pwrite = stdout.fileno()

io.UnsupportedOperation: fileno
```

Environment:

Python 3.5.1
Django==1.9.4

**Comment by chrisspen** [comment]
Which version of chroniker are you using? I can't reproduce this error in master.
